# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-02 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitoreo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('fuente', models.CharField(max_length=100)),
                ('fecha', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('codificacion', models.CharField(max_length=100)),
                ('cc', models.CharField(max_length=100)),
                ('hosting', models.CharField(max_length=100)),
                ('curl_ulti', models.CharField(max_length=500)),
                ('curl_actual', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='Ejemplo',
            new_name='correo',
        ),
        migrations.RenameField(
            model_name='correo',
            old_name='apellido',
            new_name='asunto',
        ),
        migrations.RenameField(
            model_name='correo',
            old_name='fuente',
            new_name='desde',
        ),
        migrations.RenameField(
            model_name='correo',
            old_name='nombre',
            new_name='para',
        ),
    ]
