# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-02 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0002_auto_20180602_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='Codigoestadohistorico',
            fields=[
                ('id_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
            ],
            options={
                'db_table': 'codigoestadohistorico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id_comentario', models.AutoField(primary_key=True, serialize=False)),
                ('numlinea', models.IntegerField(blank=True, null=True)),
                ('hash', models.CharField(blank=True, max_length=32, null=True)),
                ('tipo', models.BooleanField()),
            ],
            options={
                'db_table': 'comentarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dominiowhois',
            fields=[
                ('id_dominio', models.AutoField(primary_key=True, serialize=False)),
                ('domain_name', models.CharField(max_length=50)),
                ('created_on', models.CharField(blank=True, max_length=30, null=True)),
                ('expiration_date', models.CharField(blank=True, max_length=30, null=True)),
                ('last_updated_on', models.CharField(blank=True, max_length=30, null=True)),
                ('registrar', models.CharField(blank=True, max_length=30, null=True)),
                ('url', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'dominiowhois',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ipwhois',
            fields=[
                ('id_ip', models.AutoField(primary_key=True, serialize=False)),
                ('inetnum', models.CharField(blank=True, max_length=30, null=True)),
                ('status', models.CharField(blank=True, max_length=30, null=True)),
                ('autnum', models.CharField(blank=True, max_length=30, null=True)),
                ('owner', models.CharField(blank=True, max_length=50, null=True)),
                ('ownerid', models.CharField(blank=True, max_length=30, null=True)),
                ('responsable', models.CharField(blank=True, max_length=30, null=True)),
                ('direccion', models.CharField(blank=True, max_length=30, null=True)),
                ('country', models.CharField(max_length=30)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('ip', models.CharField(blank=True, max_length=15, null=True, unique=True)),
            ],
            options={
                'db_table': 'ipwhois',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lineas',
            fields=[
                ('id_linea', models.AutoField(primary_key=True, serialize=False)),
                ('numlinea', models.IntegerField(blank=True, null=True)),
                ('hash', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'lineas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MonitoreoCorreo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('para', models.CharField(max_length=100)),
                ('asunto', models.CharField(max_length=100)),
                ('desde', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'monitoreo_correo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SitiosPhishing',
            fields=[
                ('id_sitio', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=100)),
                ('dominio', models.CharField(max_length=100)),
                ('nombre_archivo', models.CharField(blank=True, max_length=50, null=True)),
                ('ofuscacion', models.CharField(blank=True, max_length=10, null=True)),
                ('md5_archivo', models.CharField(blank=True, max_length=32, null=True)),
                ('estado', models.CharField(blank=True, max_length=25, null=True)),
                ('captura', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'db_table': 'sitios_phishing',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='correo',
        ),
        migrations.DeleteModel(
            name='Monitoreo',
        ),
    ]
