# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-03 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0003_auto_20180602_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id_contacto', models.AutoField(primary_key=True, serialize=False)),
                ('entidad', models.CharField(blank=True, max_length=30, null=True)),
                ('kind', models.CharField(blank=True, max_length=30, null=True)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('role', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'contacto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id_direccion', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'direccion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id_email', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'email',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Entidades',
            fields=[
                ('id_entidades', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'entidades',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id_network', models.AutoField(primary_key=True, serialize=False)),
                ('cidr_field', models.CharField(blank=True, db_column='cidr_', max_length=30, null=True)),
                ('country', models.CharField(blank=True, max_length=30, null=True)),
                ('end_address', models.CharField(blank=True, max_length=30, null=True)),
                ('handle', models.CharField(blank=True, max_length=50, null=True)),
                ('ip_version', models.CharField(blank=True, max_length=30, null=True)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('parent_handle', models.CharField(blank=True, max_length=30, null=True)),
                ('start_address', models.CharField(blank=True, max_length=30, null=True)),
                ('type', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'network',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id_sector', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'sector',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('id_telefono', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'telefono',
                'managed': False,
            },
        ),
    ]
